services:
  foodies:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: foodies
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db
  db:
    image: postgres:14
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: foodies
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: